### ISSUE TITLE
Add ability to specify license information

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata_lib#245]
The JSON schema defining a HEPData submission has provision for a [`data_license`](https://github.com/HEPData/hepdata-validator/blob/bfcd4fd2c3bec027816944a60ca92a270e1c356b/hepdata_validator/schemas/1.1.1/submission_schema.json#L31-L37) (comprising a `name`, `url` and optional `description`) for individual tables.  It also supports a [`license`](https://github.com/HEPData/hepdata-validator/blob/bfcd4fd2c3bec027816944a60ca92a270e1c356b/hepdata_validator/schemas/1.1.1/additional_resources_schema.json#L12-L18) for additional resources.  An example of use is given in [`submission.yaml`](https://github.com/HEPData/hepdata-submission/blob/main/examples/submission/TestHEPSubmission/submission.yaml) used in [`TestHEPSubmission.zip`](https://github.com/HEPData/hepdata-submission/blob/main/examples/submission/TestHEPSubmission.zip) and in the [submission documentation](https://hepdata-submission.readthedocs.io/en/latest/submission_yaml.html#full-example).  By default, the [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) license applies, as explained in the [HEPData Terms of Use](https://www.hepdata.net/terms).

The [`add_additional_resource`](https://github.com/HEPData/hepdata_lib/blob/f194e14928538a3f62a6e6373e0df03d59bee23c/hepdata_lib/__init__.py#L58C9-L58C32) function of `hepdata_lib` should be extended to accept an optional `license` argument (a Python dictionary containing `name`, `url` and optional `description`).  The `Table` class should also be extended to include a new method `add_data_license` taking arguments `name`, `url` and optional `description`.

See also HEPData/hepdata#740.

**Comment by GraemeWatt** [comment]
Documentation should be added to `hepdata_lib` explaining how to add a license to either an additional resource file or a data table.  As an example, the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license could be used.
```yaml
name: CC BY 4.0
url: https://creativecommons.org/licenses/by/4.0/
description: This license enables reusers to distribute, remix, adapt, and build upon the material in any medium or format, so long as attribution is given to the creator.
```
