### ISSUE TITLE
Possible workspace.json file submission + symerrors submission

### ISSUE THREAD

**Issue by AndriiPovsten** [HEPData/hepdata_lib#252]
Is it possible to submit the workspace.json as a 'one separate submission' for the HEPData?
Since looking at the examples of submitted data the workspace files are only in the additional_resources in the submission.yaml file.
And is ROOT a mandatory dependency for the hepdata_lib?
Also for me the uncertainties submission is a bit tricky.
I was using this [tutorial](https://github.com/HEPData/hepdata_lib/blob/main/examples/reading_scikithep_histograms.ipynb) which provides a nice explanation of how to create the tables for the submission. 
And the uncertainties, were added by `hist.intervals.poisson_interval(s, s2)` , not just as a list of numbers.
In my case I only have a symerrors (+/-) which are located in a list/dictionary, what is the way of submitting them?
  - I mean, is it possible to create the symerror section, something like this:
```
 
      - value: 4.71
        errors:
          - symerror: 2.18
      - value: 30.95
        errors:
          - symerror: 6.61 
      - value: 73.35
        errors:
          - symerror: 15.77
 
```
Or should it be better just to have a values already as a dictionary? Since the:

```
unc1 = Uncertainty("A symmetric uncertainty", is_symmetric=True)
unc1.values = f["W+jets"]
tab1d.add_uncertainty(unc1)
```

Gives such an error:
 `'Table' object has no attribute 'add_uncertainty'`
@clelange
